config/routes.rb
Manthan::Application.routes.draw do

  resources :trips do
    collection do
      post 'reimburse'
    end
  end

  root to: 'participants#index'
  devise_for :admins

  resources :admins

  resources :teams do
    collection do
      post 'update_receiver'
    end
  end

  get 'participants/frisking'

  resources :participants do
    collection do
      get 'enter'
      get 'frisk'
    end
  end

end

app/models/trip.rb
class Trip < ActiveRecord::Base
  attr_accessible :f_max_remb, :f_reason, :f_remb_amt, :f_remb_eligible, :pid, :r_max_remb, :r_reason, :r_remb_amt, :r_remb_eligible, :attending_status, :f_ticket, :r_ticket, :hotel
  self.primary_key= :pid

  belongs_to :participant , :foreign_key => "pid"
  #validates :f_remb_amt, numericality: { only_integer: true }
  #validates :r_remb_amt, numericality: { only_integer: true }

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  # GET /trips
  # GET /trips.json

  before_filter :authenticate_admin!

  def index
    @trips = Trip.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trips }
    end
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
    @trip = Trip.find(params[:id])

    render :partial => 'trips/show'
    #page.replace_html 'dialog-message' ,:partial => 'trips/show'
    #respond_to do |format|
    #  format.html # show.html.erb
    #  format.js
    #  on { render :partial => 'trips/show' }
    #
    #end
  end

  # GET /trips/new
  # GET /trips/new.json
  def new
    @trip = Trip.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @trip }
    end
  end

  # GET /trips/1/edit
  def edit
    @trip = Trip.find(params[:id])
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(params[:trip])

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render json: @trip, status: :created, location: @trip }
      else
        format.html { render action: "new" }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trips/1
  # PUT /trips/1.json
  def update
    @trip = Trip.find(params[:id])

    respond_to do |format|
      if @trip.update_attributes(params[:trip])
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy

    respond_to do |format|
      format.html { redirect_to trips_url }
      format.json { head :no_content }
    end
  end

  def reimburse

    @trip = Trip.find_by_pid(params[:id])

    if params[:f_amt] == "" or params[:r_amt] == "" then
      render :json => {:id => params[:id], :status => 'false', :message => 'Please enter both - Forward amount and Reverse amount'}
    else
      if !(params[:f_amt].to_i.to_s ==  params[:f_amt]) or !(params[:r_amt].to_i.to_s ==  params[:r_amt]) then
        render :json => {:id => params[:id], :status => 'false', :message => 'Please enter an integer amount'}

      elsif      @trip.f_remb_amt.nil? and @trip.r_remb_amt.nil? then

      @trip.f_remb_amt = params[:f_amt]
      @trip.r_remb_amt = params[:r_amt]
      @trip.save
      render :json => {:id => params[:id], :status => 'true', :message => 'Reimbursed', :f_amt => params[:f_amt], :r_amt => params[:r_amt]}
      else
        render :json => {:id => params[:id], :status => 'reimbursed', :message => 'Already Reimbursed', :f_amt => @trip.f_remb_amt, :r_amt => @trip.r_remb_amt}
      end


    end

  end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_form.html.erb
<%= form_for(@trip) do |f| %>
  <% if @trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% @trip.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pid %><br />
    <%= f.number_field :pid %>
  </div>
   <div class="field">
    <%= f.label :f_remb_amt %><br />
    <%= f.number_field :f_remb_amt %>
  </div>
  <div class="field">
    <%= f.label :r_remb_amt %><br />
    <%= f.number_field :r_remb_amt %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trips/_show.html.erb
<p id="notice"><%= notice %></p>

<div class="">


 <p>
  <b>Pid:</b>
  <%= @trip.pid %>
</p>

<!--<p>-->
  <!--<b>F remb eligible:</b>-->
  <!--<%= @trip.f_remb_eligible %>-->
<!--</p>-->

<!--<p>-->
  <!--<b>F reason:</b>-->
  <!--<%= @trip.f_reason %>-->
<!--</p>-->

<!--<p>-->
  <!--<b>F max remb:</b>-->
  <!--<%= @trip.f_max_remb %>-->
<!--</p>-->

<p>
  <b>Forward Reimbursed Amount</b>
  <%= @trip.f_remb_amt %>
</p>

<!--<p>-->
  <!--<b>R remb eligible:</b>-->
  <!--<%= @trip.r_remb_eligible %>-->
<!--</p>-->

<!--<p>-->
  <!--<b>R reason:</b>-->
  <!--<%= @trip.r_reason %>-->
<!--</p>-->

<!--<p>-->
  <!--<b>R max remb:</b>-->
  <!--<%= @trip.r_max_remb %>-->
<!--</p>-->

<p>
  <b>Return Reimbursed Amount</b>
  <%= @trip.r_remb_amt %>
</p>

  <p>
    <b>Team Name</b>
    <%= @trip.participant.team.name %>
  </p>
  <p>
    <b>College</b>
    <%= @trip.participant.college %>
  </p>
  <p>
    <b>Attending</b>
    <%= @trip.attending_status %>
  </p>

  <p>
    <b>Forward Ticket Status</b>
    <%= @trip.f_ticket %>
  </p>

  <p>
    <b>Reverse Ticket Status</b>
    <%= @trip.r_ticket %>
  </p>
</div>

app/views/trips/edit.html.erb
<h1>Editing trip</h1>

<%= render 'form' %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<script>

    function mysum(id){
       $('#calc_'+id).html(parseInt($('#r_'+id).val()==''?'0':$('#r_'+id).val())+ parseInt($('#f_'+id).val()==''?'0': $('#f_'+id).val()))
    }


    function dialogue(){
        $( "#dialog-message" ).dialog({
            modal: true,
            height: 450,
            width: 350,
            buttons: {
                Ok: function() {
                    $( this ).dialog( "close" );
                }
            }
        });
    }


    function on_submit_click(id) {

        $.ajax({
            type:"POST",
            url:"<%=reimburse_trips_url%>",
            data:{f_amt:$("#f_" + id.toString()).val(),r_amt:$("#r_" + id.toString()).val(), id:id },
            success:function (data, textStatus) {
                if(data['status'] == 'true'){
                    var elem = $("#" + data['id']).parent()
                    $("#" + data['id']).parent().html('<p>' + data['message'] + " </p><a target='_blank' href='/trips/"+data['id']+ "/edit'>Edit</a>");
                    elem.css('background-color', "#31973d");
                    $("#f_"+data['id']).parent().html(data['f_amt']);
                    $("#r_"+data['id']).parent().html(data['r_amt']);
                }else if(data['status'] == 'reimbursed'){
                    var elem = $("#" + data['id']).parent()
                    $("#" + data['id']).parent().html('<p>' + data['message'] + " </p><a target='_blank' href='/trips/"+data['id']+ "/edit'>Edit</a>");
                    elem.css('background-color', "#ea4141");
                $("#f_"+data['id']).parent().html(data['f_amt']);
                $("#r_"+data['id']).parent().html(data['r_amt']);
                    $("#notice").html(data['message']);
                }
                else{$("#notice").html(data['message']);
                }
            },
            dataType:'json'
        });
        return false;
    }

    function show_on_click(id) {

        $.ajax({
            type:"GET",
            url:"<%=trips_url%>/"+id,
            data:{id:id },
            success:function (data, textStatus) {
//                if(data['status'] == 'true'){
//                       alert("hello");
                    $("#dialog-message").html(data);
                dialogue();
//                }else
//                {$("#notice").html(data['message']);
//                }
            },
            dataType:'html'
        });
        return false;
    }

    $(document).ready(function () {
        $('#trips').dataTable({
        });


    });
</script>

<table id="trips" class="table table-bordered table-striped">
  <thead>
  <tr>
    <th>Pid</th>
    <th>Name</th>
    <th>Team Name</th>
    <th>Boarding City</th>
    <th>Forward eligibility</th>
    <th>Forward Reason</th>
    <th>Forward Max Amount</th>
    <th>Forward Reimbursed Amount</th>
    <th>Return eligibility</th>
    <th>Return Reason</th>
    <th>Return Max Amount</th>
    <th>Return Reimbursed Amount</th>
    <th>Total</th>
    <th></th>
    <th>Details</th>
  </tr>
  </thead>
  <tbody>
  <% @trips.each do |trip| %>
      <tr>
        <td><%= trip.pid %></td>
        <td><%= trip.participant.fname.to_s + " " + trip.participant.lname.to_s %></td>
        <td><%= trip.participant.team.name %></td>
        <td><%= trip.participant.bcity %></td>
        <td><%= trip.f_remb_eligible %></td>
        <td><%= trip.f_reason %></td>
        <td><%= trip.f_max_remb %></td>
        <% if !trip.f_remb_amt.blank? then %>
            <td>
              <%= trip.f_remb_amt %>
            </td>
        <% else %>
            <td>
              <div class="field"><input id="f_<%= trip.id %>" type="text" style="width:40px; " onchange="mysum(<%= trip.id%>)"></div>
            </td>
        <% end %>
        <td><%= trip.r_remb_eligible %></td>
        <td><%= trip.r_reason %></td>
        <td><%= trip.r_max_remb %></td>
        <% if !trip.r_remb_amt.blank? then %>
            <td>
              <%= trip.r_remb_amt %>
            </td>
        <% else %>
            <td>
              <div class="field"><input id="r_<%= trip.id %>" type="text" style="width:40px; " onchange="mysum(<%= trip.id%>)"></div>
            </td>
        <% end %>
        <td><div id="calc_<%= trip.id %>">
          <% if !trip.r_remb_amt.blank? and !trip.f_remb_amt.blank? then %>
              <%=trip.r_remb_amt.to_i + trip.f_remb_amt.to_i	  %>
          <% else %>

          <% end %>
        </div></td>
        <% if !trip.r_remb_amt.blank? and !trip.f_remb_amt.blank? then %>
            <td>
              <div class="action"><p>Reimbursed </p> <%= link_to 'Edit', edit_trip_path(trip) %></div>
            </td>
        <% else %>
            <td>
              <div class="action"><input name="id" id="<%= trip.id %>" data-disable_with = "Please wait..." receiver="" target="_blank" type="submit" value="Submit" onclick="on_submit_click(<%= trip.id%>);"></div>
            </td>
        <% end %>
        <td><a  href="#"  id ="dialog_<%=trip.id%>" onclick = "show_on_click(<%= trip.id %>);">Show</a> </td>

      </tr>
  <% end %>
  </tbody>
</table>
<div id="dialog-message" class=""></div>
<br/>

<%= link_to 'New Trip', new_trip_path %>

app/views/trips/new.html.erb
    <h1>New trip</h1>

<%= render 'form' %>

<%= link_to 'Back', trips_path %>

app/views/trips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Pid:</b>
  <%= @trip.pid %>
</p>

<p>
  <b>F remb eligible:</b>
  <%= @trip.f_remb_eligible %>
</p>

<p>
  <b>F reason:</b>
  <%= @trip.f_reason %>
</p>

<p>
  <b>F max remb:</b>
  <%= @trip.f_max_remb %>
</p>

<p>
  <b>F remb amt:</b>
  <%= @trip.f_remb_amt %>
</p>

<p>
  <b>R remb eligible:</b>
  <%= @trip.r_remb_eligible %>
</p>

<p>
  <b>R reason:</b>
  <%= @trip.r_reason %>
</p>

<p>
  <b>R max remb:</b>
  <%= @trip.r_max_remb %>
</p>

<p>
  <b>R remb amt:</b>
  <%= @trip.r_remb_amt %>
</p>


<%= link_to 'Edit', edit_trip_path(@trip) %> |
<%= link_to 'Back', trips_path %>

app/views/trips/show.js.erb
page.replace_html('dialog-message',render(@trip))