config/routes.rb
Manthan::Application.routes.draw do

  resources :trips do
    collection do
      post 'reimburse'
    end
  end

  root to: 'participants#index'
  devise_for :admins

  resources :admins

  resources :teams do
    collection do
      post 'update_receiver'
    end
  end

  get 'participants/frisking'

  resources :participants do
    collection do
      get 'enter'
      get 'frisk'
    end
  end

end

app/models/participant.rb
class Participant < ActiveRecord::Base
  attr_accessible :age, :bcity, :college, :email, :fname, :gender, :lname, :phone, :pid, :teligible, :entry,:team_id
  set_primary_key :pid
  belongs_to :team, :class_name => "Team", :foreign_key => "team_id"
  has_one :trip, :foreign_key => "pid"

end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  # GET /participants
  # GET /participants.json

  before_filter :authenticate_admin!

  def index
    @participants = Participant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @participants }
    end
  end

  # GET /participants/1
  # GET /participants/1.json
  def show
    @participant = Participant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @participant }
    end
  end

  # GET /participants/new
  # GET /participants/new.json
  def new
    @participant = Participant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @participant }
    end
  end

  # GET /participants/1/edit
  def edit
    @participant = Participant.find(params[:id])
  end

  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.new(params[:participant])

    respond_to do |format|
      if @participant.save
        format.html { redirect_to @participant, notice: 'Participant was successfully created.' }
        format.json { render json: @participant, status: :created, location: @participant }
      else
        format.html { render action: "new" }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /participants/1
  # PUT /participants/1.json
  def update
    @participant = Participant.find(params[:id])

    respond_to do |format|
      if @participant.update_attributes(params[:participant])
        format.html { redirect_to @participant, notice: 'Participant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    @participant = Participant.find(params[:id])
    @participant.destroy

    respond_to do |format|
      format.html { redirect_to participants_url }
      format.json { head :no_content }
    end
  end


  def enter
    @participant = Participant.find_by_pid(params[:part_id])
    @eligibility = @participant.trip.f_remb_eligible == 'Eligible' || @participant.trip.r_remb_eligible == 'Eligible'

    if   @participant.entry? then
      render :json => {:id => params[:part_id], :status => 'false', :message => 'Already Registered', :color => 'red'}
    else
      @participant.update_attribute(:entry, true)
      render :json => {:id => params[:part_id], :status => 'true', :message => 'Accepted', :color => 'green', :eligibility => "#{@eligibility}"}

    end

  end

  def frisking
    @participants = Participant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @participants }
    end

  end

  def frisk
    @participant = Participant.find_by_pid(params[:part_id])

    if   @participant.frisk? then
      render :json => {:id => params[:part_id], :status => 'false', :message => 'Already Cleared', :color => 'red'}
    else
      @participant.update_attribute(:frisk, true)
      render :json => {:id => params[:part_id], :status => 'true', :message => 'Cleared', :color => 'green'}
    end

  end

end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/participants/_form.html.erb
<%= form_for(@participant) do |f| %>
  <% if @participant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@participant.errors.count, "error") %> prohibited this participant from being saved:</h2>

      <ul>
      <% @participant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pid %><br />
    <%= f.number_field :pid %>
  </div>
  <div class="field">
    <%= f.label :college %><br />
    <%= f.text_field :college %>
  </div>
  <div class="field">
    <%= f.label :fname %><br />
    <%= f.text_field :fname %>
  </div>
  <div class="field">
    <%= f.label :lname %><br />
    <%= f.text_field :lname %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.number_field :phone %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :gender %><br />
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :bcity %><br />
    <%= f.text_field :bcity %>
  </div>
  <div class="field">
    <%= f.label :teligible %><br />
    <%= f.number_field :teligible %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/participants/edit.html.erb
<h1>Editing participant</h1>

<%= render 'form' %>

<%= link_to 'Show', @participant %> |
<%= link_to 'Back', participants_path %>

app/views/participants/enter.html.erb
<p>You are finally here</p>

app/views/participants/frisking.html.erb
<script>
    $(document).ready(function () {
        $('#participants').dataTable({
        });
        $('a[data-remote]').live('ajax:success', function (evt, data) {
            $('#' + 'accept_' + data['id']).html(data['message']);
            if (data['status'] == 'true') {
                $('#' + 'accept_' + data['id']).css('background-color', "#31973d");
            } else {
                $('#' + 'accept_' + data['id']).css('background-color', "#ea4141");
            }
        });
    });

</script>



<table id="participants" cellpadding="0" cellspacing="0" border="0" class="table table-bordered table-striped">
  <thead>
  <tr>
    <th>Pid</th>
    <th>College</th>
    <th>Team Name</th>
    <th>Name</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Gender</th>
    <th>Boarding city</th>
    <th>Attending</th>

    <th>Status</th>
  </tr>
  </thead>
  <tbody>
  <% @participants.each do |participant| %>
      <% @gender = Array.new ["", "M", "F"] %>
      <tr>
        <td><%= participant.pid %></td>
        <td><%= participant.college %></td>

        <% if participant.college[0..3]=="IWTA" or participant.college[0..1]=="CA" then %>
            <td>NA</td>
        <% else %>
            <td><%= participant.team.name %></td>
        <% end %>

        <td><%= participant.fname.to_s + " " + participant.lname.to_s %></td>
        <td><%= participant.email %></td>
        <td><%= participant.phone %></td>
        <td><%= @gender[participant.gender.to_i] %></td>
        <td><%= participant.bcity %></td>
        <% if participant.college[0..3]=="IWTA" then %>
            <td>IWTA</td>
        <% elsif participant.college[0..1]=="CA" then %>
            <td>CA</td>
        <% else %>
            <td><%= participant.trip.attending_status %></td>
        <% end %>
        <% if participant.frisk? then %>
            <td>Already Registered</td>
        <% else %>
            <td id="accept_<%= participant.pid %>"><%= link_to 'Clear', {:action => 'frisk', :part_id => participant.pid}, :remote => TRUE, :disable_with => 'Please wait...', :'data-update-target' => 'update-container' %></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

<br/>

<%= link_to 'New Participant', new_participant_path %>

app/views/participants/index.html.erb
<script>
    function dialogue(){
        $( "#dialog-message" ).dialog({
            modal: true,
            height: 150,
            width: 300,
            buttons: {
                Ok: function() {
                    $( this ).dialog( "close" );
                }
            }
        });
    }

    $(document).ready(function () {
        $('#participants').dataTable({
        });
        $('a[data-remote]').live('ajax:success', function (evt, data) {
            $('#' + 'accept_' + data['id']).html(data['message']);
            if (data['status'] == 'true') {
                $('#' + 'accept_' + data['id']).css('background-color', "#31973d");
                if(data['eligibility'] == 'true'){
                $("#dialog-message").html('Eligible for Reimbursement');
                dialogue();
                }
            } else {
                $('#' + 'accept_' + data['id']).css('background-color', "#ea4141");
            }
        });
    });

</script>



<table id="participants" cellpadding="0" cellspacing="0" border="0" class="table table-bordered table-striped">
  <thead>
  <tr>
    <th>Pid</th>
    <th>College</th>
    <th>Team Name</th>
    <th>Name</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Gender</th>
    <th>Boarding city</th>
    <th>Attending</th>

    <th>Status</th>
  </tr>
  </thead>
  <tbody>
  <% @participants.each do |participant| %>
      <% @gender = Array.new ["", "M", "F"] %>
      <tr>
        <td><%= participant.pid %></td>
        <td><%= participant.college %></td>

        <% if participant.college[0..3]=="IWTA" or participant.college[0..1]=="CA" then %>
            <td>NA</td>
        <% else %>
            <td><%= participant.team.name %></td>
        <% end %>

        <td><%= participant.fname.to_s + " " + participant.lname.to_s %></td>
        <td><%= participant.email %></td>
        <td><%= participant.phone %></td>
        <td><%= @gender[participant.gender.to_i] %></td>
        <td><%= participant.bcity %></td>
        <% if participant.college[0..3]=="IWTA" then %>
            <td>IWTA</td>
        <% elsif participant.college[0..1]=="CA" then %>
            <td>CA</td>
        <% else %>
            <td><%= participant.trip.attending_status %></td>
        <% end %>
        <% if participant.entry? then %>
            <td>Already Registered</td>
        <% else %>
            <td id="accept_<%= participant.pid %>"><%= link_to 'Accept', {:action => 'enter', :part_id => participant.pid}, :remote => TRUE, :disable_with => 'Please wait...', :'data-update-target' => 'update-container' %></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>
<div id="dialog-message" class=""></div>

<br/>

<%= link_to 'New Participant', new_participant_path %>

app/views/participants/index.js.erb
$(document).ready(function() {
    $('#participants').dataTable({
    });

} );

app/views/participants/new.html.erb
<h1>New participant</h1>

<%= render 'form' %>

<%= link_to 'Back', participants_path %>

app/views/participants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Pid:</b>
  <%= @participant.pid %>
</p>

<p>
  <b>College:</b>
  <%= @participant.college %>
</p>

<p>
  <b>Fname:</b>
  <%= @participant.fname %>
</p>

<p>
  <b>Lname:</b>
  <%= @participant.lname %>
</p>

<p>
  <b>Email:</b>
  <%= @participant.email %>
</p>

<p>
  <b>Phone:</b>
  <%= @participant.phone %>
</p>

<p>
  <b>Age:</b>
  <%= @participant.age %>
</p>

<p>
  <b>Gender:</b>
  <%= @participant.gender %>
</p>

<p>
  <b>Bcity:</b>
  <%= @participant.bcity %>
</p>

<p>
  <b>Teligible:</b>
  <%= @participant.teligible %>
</p>


<%= link_to 'Edit', edit_participant_path(@participant) %> |
<%= link_to 'Back', participants_path %>