config/routes.rb
Manthan::Application.routes.draw do

  resources :trips do
    collection do
      post 'reimburse'
    end
  end

  root to: 'participants#index'
  devise_for :admins

  resources :admins

  resources :teams do
    collection do
      post 'update_receiver'
    end
  end

  get 'participants/frisking'

  resources :participants do
    collection do
      get 'enter'
      get 'frisk'
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Manthan</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
  <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />

  <style>
    .navbar {
        margin-bottom: 5px;
    }
    .form-signin {
        max-width: 300px;
        padding: 19px 29px 29px;
        margin: 0 auto 20px;
        background-color: #fff;
        border: 1px solid #e5e5e5;
        -webkit-border-radius: 5px;
        -moz-border-radius: 5px;
        border-radius: 5px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
        -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
        box-shadow: 0 1px 2px rgba(0,0,0,.05);
    }
     .red{
         background-color: #f08080;
     }
     .orange{
         background-color: orange;
     }
     .green{
         background-color: #90ee90;
     }
  </style>
</head>
<body style="padding-top: 60px; padding-bottom: 40px; background-color: #F5F5F5;" >
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="brand" href="#">Manthan Registrations</a>
      <div class="nav-collapse collapse">
        <p class="navbar-text pull-right">
          <%if admin_signed_in? then %>
          Logged in as <a href="#" class="navbar-link"><%=current_admin.email %></a>|
              <%= link_to "Sign out", destroy_admin_session_path, :method => :delete, :class => 'navbar-link' %>
          <%else%>
              <a href="<%=new_admin_session_path%>" class="navbar-link" >Sign In</a>
          <% end %>
        </p>
        <ul class="nav">
          <!--<li class="active"><a href="<%= participants_url%>">Registration</a></li>-->
          <!--<li><a href="<%= teams_url%>">Certificates</a></li>-->
          <!--<li><a href="<%= trips_url %>">Reimbursement</a></li>-->
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>
<div class="container-fluid">
      <div class="alert alert-error" id="notice">
        <%=notice.blank? ? notice : "" %>
      </div>
<%= yield %>
</div>
</body>
</html>